version: '3'

services:
  webchat:
    image: docker.nexus.gpchatbot.archi-lab.io/chatbot/webchat:latest
    ports:
      - "80:80"
    environment:
      - ROOT=/usr/share/nginx/html/static
    command: ["/bin/bash", "/etc/conf.d/setenv.sh", "nginx", "-g", "daemon off;"]
