version: '3'

services:
  webchat:
    image: docker.nexus.gpchatbot.archi-lab.io/chatbot/webchat:latest
    restart: always
    ports:
      - "80:80"
    environment:
    - ROOT=/usr/share/nginx/html/static
    command: bash -c "/etc/nginx/conf.d/setenv.sh && nginx-debug -g \"daemon off;\" "
