version: '3'

services:
  webchat:
    image: docker.nexus.gpchatbot.archi-lab.io/chatbot/webchat:latest
    ports:
    - "80:80"
    environment:
    # path to http-server entry point
    - ROOT=/usr/share/nginx/html/static
    # will set envs to nginx config files and run nginx
    command: bash -c "/etc/nginx/conf.d/setenv.sh && nginx-debug -g \"daemon off;\" "

