version: '3'

services:
  webchat:
    image: docker.nexus.gpchatbot.archi-lab.io/chatbot/webchat
    restart: always
    ports:
      - "80:8080"
    networks:
    - chatbot
networks:
  chatbot:
    external: true
